---
apiVersion: v1
kind: Service
metadata:
  name: service-sprint2-http-horse
spec:
  selector:
    kind: pod-sprint2-http-horse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer