---
apiVersion: v1
kind: Service
metadata:
  name: sprint2-http-horse
spec:
  selector:
    kind: httpd-horse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: sprint2-nginx-cow
spec:
  selector:
    kind: nginx-cow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: sprint2-nginx-whale
spec:
  selector:
    kind: nginx-whale
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sprint2-http-horse
spec:
  replicas: 2
  selector:
    matchLabels:
      kind: pod-sprint2-http-horse
  template:
    metadata:
      labels:
        kind: pod-sprint2-http-horse
    spec:
      containers:
      - name: httpd
        image: Nume Imagine Din Private Registry
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sprint2-nginx-cow
spec:
  replicas: 2
  selector:
    matchLabels:
      kind: pod-sprint2-nginx-cow
  template:
    metadata:
      labels:
        kind: pod-sprint2-nginx-cow
    spec:
      containers:
        - name: nginx
          image: Nume Imagine din Private Registry
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sprint2-nginx-whale
spec:
  replicas: 2
  selector:
    matchLabels:
      kind: pod-sprint2-nginx-whale
  template:
    metadata:
      labels:
        kind: pod-sprint2-nginx-whale
    spec:
      containers:
        - name: nginx
          image: Nume Imagine din Private Registry
          ports:
            - containerPort: 80